zk:
  servers: 10.100.16.44:2181
  max-total: 10
  max-idle: 6
  min-idle: 1
  session-timeout: 30000
  connection-timeout: 130000
server:
  port: 8084
  servlet:
    context-path: /
logging:
  config: classpath:config/logback-spring.xml